# Generated by Django 2.2.3 on 2019-07-31 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('product_type', models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('AUCTION', 'Auction'), ('SERVICE', 'Service')], max_length=30, null=True)),
                ('duration_measure', models.CharField(blank=True, choices=[('DAY', 'Day'), ('HOUR', 'Hour')], max_length=4, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('low_stock', models.BooleanField(default=False)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('mark_as_new', models.BooleanField(default=False)),
                ('new_start', models.DateTimeField(blank=True, null=True)),
                ('new_end', models.DateTimeField(blank=True, null=True)),
                ('not_returnable', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('allow_reviews', models.BooleanField(default=False)),
                ('vendor_comments', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('sales_rate', models.FloatField(blank=True, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('call_for_price', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lenght', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sold', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('reserved_start_date', models.DateField(blank=True, null=True)),
                ('reserved_start_time', models.TimeField(blank=True, null=True)),
                ('reserved_end_date', models.DateField(blank=True, null=True)),
                ('reserved_end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
