# Generated by Django 2.2.3 on 2019-08-06 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190802_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='photos.Album'),
        ),
    ]
