# Generated by Django 2.2.3 on 2019-08-13 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('catalog', '0005_auto_20190806_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='acl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='users.Acl'),
        ),
        migrations.AddField(
            model_name='product',
            name='acl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='users.Acl'),
        ),
    ]
