# Generated by Django 2.2.3 on 2019-08-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190813_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_aux',
            field=models.BooleanField(default=False),
        ),
    ]
