# Generated by Django 2.2.3 on 2019-08-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190731_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('Dispensary', 'Dispensary'), ('Grower', 'Grower'), ('Processor', 'Processor'), ('Tester', 'Tester')], max_length=30),
        ),
    ]
