# Generated by Django 2.2.3 on 2019-08-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_auxilary',
            field=models.BooleanField(default=False),
        ),
    ]
