# Generated by Django 2.2.3 on 2019-08-14 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vendor_is_auxilary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='is_auxilary',
        ),
    ]
