# Generated by Django 2.2.3 on 2019-07-31 16:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('time', models.TimeField(blank=True, help_text='Please use the following format: <em>HH:MM:SS<em>')),
                ('attendees', models.ManyToManyField(blank=True, related_name='events', to='accounts.Customer')),
                ('vendor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.Vendor')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.Event')),
                ('product', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
    ]
