# Generated by Django 2.2.3 on 2019-08-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_album_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='cover',
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
