# Generated by Django 2.2.3 on 2019-08-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20190802_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='default',
        ),
        migrations.AddField(
            model_name='album',
            name='default',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
