# Generated by Django 2.2.3 on 2019-08-13 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20190803_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='default',
        ),
    ]
